
const TagTypes = {
    users: "Users",
    exportedUsers: "ExportedUsers",
    categories: "Categories",
    exportCategories: "ExportCategories",
    categoryDropDown: "CategoryDropDown",
    profile: "Profile",
    total: "Total",
    userGrowth: "UserGrowth",
    candidates: "Candidates",
    stats: "Stats",
    contacts: "Contacts",
    subscribers: "Subscribers",
    admins: "Admins",
    information: "Information",
    products: "Products",
    exportProducts: "ExportProducts",
    featureProducts: "FeatureProducts",
    bestSellerProducts: "BestSellerProducts",
    product: "Product",
    policy: "Policy",
    orders: "Orders",
    exportOrders: "ExportOrders",
    order: "Order",
    incomeGrowth: "incomeGrowth",
    subsbscribers: "Subscribers",
    brands: "Brands",
    exportBrands: "ExportBrands",
    brandDropDown: "BrandDropDown",
    flavors: "Flavors",
    exportFlavors: "ExportFlavors",
    flavorDropDown: "FlavorDropDown",
    types: "Types",
    exportTypes: "ExportTypes",
    typeDropDown: "TypeDropDown",
    shippingCosts: "ShippingCosts"
}

export default TagTypes;